"""empty message

Revision ID: 413ac3f93344
Revises: 
Create Date: 2023-04-25 22:33:54.172660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413ac3f93344'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snils', sa.VARCHAR(length=50), nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('university', sa.VARCHAR(length=255), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('origin', sa.Boolean(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicants')
    # ### end Alembic commands ###
